problem:
  name: "Rastrigin"
  dimensions: 50
  lower_bound: -5.12
  upper_bound: 5.12

algorithm:
  pop_size: 10000
  max_generations: 300
  mutation_rate: 0.1
  crossover_rate: 0.9
  selection:
    type: "Tournament"
    tournament_size: 5

output:
  log_file: ""