problem:
  name: "Rastrigin"
  dimensions: 2
  lower_bound: -5.12
  upper_bound: 5.12

algorithm:
  backend: "DE"
  pop_size: 250
  max_generations: 100

  mutation_rate: 0.8
  crossover_rate: 0.9

  selection: # ignore
    type: "Tournament"
    tournament_size: 3

output:
  log_file: "logs/de_viz_data.csv"
